# Generated by Django 5.2.3 on 2025-06-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_promocode_order_discount_order_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('vodafone', 'Vodafone Cash'), ('instapay', 'InstaPay'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=20),
        ),
    ]
