# Generated by Django 5.2.3 on 2025-06-20 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
